### ISSUE TITLE
Can't add chart in Rancher 2.5

### ISSUE THREAD

**Issue by pdavisfmnh** [janeczku/keepalived-ingress-vip#7]
When trying to add the chart as a git repo in Rancher 2.5 I get the following error:

`symlink found at path management-state/git-repo/keepalived-ingress-vip/31c4857eacb3c3395bd30e956dad9c7cc4ff6eae797329488559cfb3573aa6de/README.md`

**Comment by janeczku** [comment]
Thanks for report @pdavisfmnh !

This indeed appears to be an upstream issue, as the  chart  works fine when added as an application catalog in the Rancher cluster manager UI.

https://github.com/rancher/rancher/issues/31882

**Comment by janeczku** [comment]
Mitigated by https://github.com/janeczku/keepalived-ingress-vip/commit/a9473a28c448378f4e33bc2fa104c5bf08e10267
